import random
random_number=random.randint(1,10)

guess_number=int(input("enter a number in the range(1,10):"))
print("the random number generated by computer is:",random_number)

if random_number==guess_number:
    print("your guess is correct!!!")
elif random_number>guess_number:
    print("your guess number is too low")
elif random_number<guess_number:
   print("your guess number is too high")
else:
     print("try again")


